proto/v1/receptor/receptor.proto

None
None
[AP-3716]
[AP-3716]: https://intersticelabs.atlassian.net/browse/AP-3716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add versioning to file structure to allow for simultaneous use of different versions.

---

.github/spellcheck.yml

Add spellcheck for github

---

go/Makefile
go/pkg/printer/printer.go
go/pkg/printer/printers.go
go/pkg/printer/string_converter.go
go/pkg/proto-utils/message.go
go/pkg/proto-utils/tr_tag.go
go/pkg/reflect-utils/utils.go
go/pkg/tabular/markdown.go
go/pkg/tabular/markdown_test.go
go/pkg/tabular/table.go
go/receptor_v1/receptor.go
go/receptor_v1/receptor_test.go

Moving proto markdown utils to API

AP-3739: Move proto markdown utils to api

---

README.md

Sequence diagrams explaining how the receptor sdk interacts with the trustero server

AP-3442: trustero API documentation

---

go/pkg/proto-utils/tr_tag.go
go/receptor_v1/receptor_test.go

Id field was not being set correctly

AP-3764: Fix tag id parsing

---

go/receptor_sdk/cmd/mock_receptor.go
go/receptor_v1/tabulator.go

Test tabulate and have cmd print evidence in tabular form in dryrun mode.
Ran gitlab receptor in debug mode and observed output.
[AP-3807]
[AP-3807]: https://intersticelabs.atlassian.net/browse/AP-3807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Have mock receptor print evidence finding in tabular form.

---

go/receptor_sdk/cmd/root.go
go/receptor_sdk/cmd/services.go

Fix case where cmd isn't fetching credentials from ntrced.
run gitlab receptor.
[AP-007]

[AP-007] Fix case where root isn't getting credentials from ntrced.

---

doc/receptor_v1/receptor.md
make/license_header.sh
proto/receptor_v1/receptor.proto

Generate proto docs
make on top level
[AP-###]

generate proto docs

---

.github/workflows/spelling.yml
go/receptor_sdk/cmd/root.go
go/receptor_sdk/receptor.go

Cmd will log errors returned by receptor.Verify|Discover|Report calls.
ran gitlab receptor and observe response.
[AP-###]

Add Error Logging

---

.github/workflows/spelling.yml

updated the check-spelling package in the workflow to use the latest
release
fix and check dependabot
[AP-007]

[AP-007] update Check-spelling in workflow

---

go/examples/gitlab_receptor/main.go
go/examples/gitlab_receptor/trr-gitlab.md

Add better comments to the GitLab example receptor. Also add .md file
none
[AP-3808]
[AP-3808]: https://intersticelabs.atlassian.net/browse/AP-3808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AP-3808] Update gitlab example comments

---

go/examples/gitlab_receptor/main.go
go/receptor_sdk/cmd/report.go

Export ExtractMetaData & RowToStructRow
-- None -- 
[AP-007]

Export ExtractMetaData & RowToStructRow

---

.github/workflows/spelling.yml

remove pull_request_target: from spell check
check on github
[AP-###]

Fix spell check

---

go/examples/gitlab_receptor/main.go
go/receptor_sdk/cmd/report.go

receptor was complaining when time was nil, added check
run receptor
[AP-###]

fix errors with time dereferencing

---

README.md

<place a description of you pull request here>
<put your test plan here. Attach screenshots via the UI.>
[AP-###]

add root level README

---

.github/actions/spelling/allow.txt

<place a description of you pull request here>
<put your test plan here. Attach screenshots via the UI.>
[AP-###]

add goreportcard to dictionary

---

.github/actions/spelling/allow.txt
.github/actions/spelling/excludes.txt
.github/actions/spelling/expect.txt
README.md
go/examples/gitlab_receptor/trr-gitlab.md

<place a description of you pull request here>
<put your test plan here. Attach screenshots via the UI.>
[AP-###]

change details in README

---

go/README.md

add client example and receptor testing instructions

add client and testing in readme

---

go/examples/gitlab_receptor/credentialInstructions.md

update credential instructions file name to match template
refresh
[AP-007]

[AP-007] Update credential Instructions file name

---

go/receptor_v1/tabulator.go

Changed how the null date Is calculated
It will have to appear here to run
[AP-007]

[AP-007] fixed how null date is calculated

---

go/examples/gitlab_receptor/main.go
go/receptor_sdk/cmd/evidenceinfo.go

Minor json output fixes
test on dev
[AP-4723]
[AP-4723]: https://intersticelabs.atlassian.net/browse/AP-4723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AP-4723] made the json work a little better

---

go/README.md
go/receptor_sdk/cmd/evidenceinfo.go

Fixed README to reflect new API changes
readme change
[AP-007]

[AP-007] evidence info readme change

---

go/receptor_sdk/cmd/verify.go

This PR fixes skipping config posting even when verify is set not to update creds
Tested locally
[AP-7516]
[AP-7516]: https://intersticelabs.atlassian.net/browse/AP-7516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AP-7516] Fix SDK to allow verify to post config

---

go/examples/gitlab_receptor/main.go
go/receptor_sdk/cmd/discover.go
go/receptor_sdk/cmd/report.go
go/receptor_sdk/cmd/scan.go
go/receptor_sdk/cmd/verify.go
go/receptor_sdk/receptor.go

This PR adds Config to Verify, Discover and Report in the sdk
Tested locally. 
[AP-7516]
[AP-7516]: https://intersticelabs.atlassian.net/browse/AP-7516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AP-7516]Add Config to Verify, Discover and Report

---

README.md

Fix README with correct function names.
N/A
[AP-8169]
[AP-8169]: https://intersticelabs.atlassian.net/browse/AP-8169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AP-8169] Update README

---

go/examples/gitlab_receptor/main.go
go/receptor_sdk/cmd/evidenceinfo.go
go/receptor_sdk/cmd/report.go
go/receptor_sdk/cmd/scan.go
go/receptor_sdk/receptor.go

Added support for report to be made in batches.
[AP-9158]
[AP-9158]: https://intersticelabs.atlassian.net/browse/AP-9158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AP-9158] Report evidence in batches

---

go/receptor_sdk/cmd/report.go
go/receptor_sdk/receptor.go

This PR add support for unstructured data as automatic evidence. 
Tested the receptor locally
[AP-9331]
[AP-9331]: https://intersticelabs.atlassian.net/browse/AP-9331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AP-9331] Document Evidence Support

---

go/receptor_sdk/client/apiclient.go

PR increases maximum message size for grpc during send.
[AP-9940]
[AP-9940]: https://intersticelabs.atlassian.net/browse/AP-9940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AP-9940]Increase max grpc send message size

---

go/examples/gitlab_receptor/main.go

gitlab sample report batch evidence close channel fix 
[AP-9948]
[AP-9948]: https://intersticelabs.atlassian.net/browse/AP-9948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AP-9948]Fix gitlab sample batch report

---

.github/workflows/ci.yml

- pin poetry version
- ci work

pin poetry version to 1.8.5

---

go/receptor_sdk/cmd/report.go

This PR adds EvidenceKey to support external record identifier through all workflow
[AP-11155]
[AP-11155]: https://intersticelabs.atlassian.net/browse/AP-11155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AP-11155]EvidenceKey in evidence
